version: '3.8'

services:
  web:
    build:
      context: .
    command: bash -c "./utils/wait_for_db.sh db 5432"
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
